# This workflow will update data.json from JHU github repository

name: Update Data

on:
  schedule:
   - cron: "0 0,8,16 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies and Sync Data
      run: |
           npm install
           npm run sync-data
    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "update data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.COVID_DATA_UPDATE }}
