# This workflow will update data.json from JHU github repository

name: Update Data

on:
  schedule:
   - cron: "0 0,8,16 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install deps
      run: |
           npm install
           npm run sync-data
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.COVID_DATA_UPDATE }}
